-- CreateTable
CREATE TABLE "Profile" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "displayName" TEXT NOT NULL,
    "age" INTEGER NOT NULL,
    "role" TEXT NOT NULL,
    "bio" TEXT NOT NULL,
    "verified" BOOLEAN NOT NULL,
    "intent" TEXT,
    "state" TEXT,
    "zip" TEXT,
    "experienceLevel" TEXT,
    "aftercare" TEXT,
    "sceneTypes" TEXT,
    "hardLimits" TEXT,
    "kinkTags" TEXT,
    "safeword" TEXT,
    "boundaries" TEXT,
    "relationshipStyle" TEXT,
    "availability" TEXT,
    "playLocation" TEXT,
    "aftercarePreferences" TEXT,
    "aftercareNotes" TEXT,
    "softLimits" TEXT,
    "limitsNotes" TEXT,
    "lastActiveAt" DATETIME,
    "boostedUntil" DATETIME,
    "photoKey" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
